version: "3.8"

services:
  frontend:
    build: frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
    ports:
      - 3000:3000

  api:
    build: api
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/mydatabase
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm run dev && npm run migrate"
    ports:
      - 3001:3001
    depends_on:
      - db

  batch:
    build: api
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/mydatabase
    volumes:
      - ./api:/usr/src/app
    command: ["npm", "run", "batch"]

    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
