export const CRYPTOCURRENCY = {
  BTC: "BTC",
  ETH: "ETH",
  BCH: "BCH",
  LTC: "LTC",
  XRP: "XRP",
  XEM: "XEM",
  XLM: "XLM",
  BAT: "BAT",
  XTZ: "XTZ",
  QTUM: "QTUM",
  ENJ: "ENJ",
  DOT: "DOT",
  ATOM: "ATOM",
  MKR: "MKR",
  DAI: "DAI",
  XYM: "XYM",
  MONA: "MONA",
  FCR: "FCR",
  ADA: "ADA",
  LINK: "LINK",
  DOGE: "DOGE",
  SOL: "SOL",
  ASTR: "ASTR",
  NAC: "NAC",
};

export const CRYPTOCURRENCY_LIST = Object.values(CRYPTOCURRENCY);
