export const VIRTUAL_CURRENCIES = {
  BTC_JPY: "BTC",
  ETH_JPY: "ETH",
  ETC_JPY: "ETC",
  LSK_JPY: "LSK",
  XRP_JPY: "XRP",
  XEM_JPY: "XEM",
  BCH_JPY: "BCH",
  MONA_JPY: "MONA",
  IOST_JPY: "IOST",
  ENJ_JPY: "ENJ",
  CHZ_JPY: "CHZ",
  IMX_JPY: "IMX",
  SHIB_JPY: "SHIB",
  AVAX_JPY: "AVAX",
  PLT_JPY: "PLT",
  FNCT_JPY: "FNCT",
  DAI_JPY: "DAI",
  WBTC_JPY: "WBTC",
  BRIL_JPY: "BRIL",
  BC_JPY: "BC",
};

export const VIRTUAL_CURRENCY_LIST = Object.values(VIRTUAL_CURRENCIES);
